### PR TITLE
Add snapcraft packaging

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by rominf** [comment]
By the way, I got the same build error on ARM64 in Ubuntu launchpad builders as in https://github.com/artempyanykh/marksman/issues/163, so I disabled this arch.

**Comment by artempyanykh** [comment]
@rominf thanks! I think we should have a fix for #163 very soon.

**Comment by artempyanykh** [comment]
@rominf #163 has been resolved. Please try re-enabling aarch64.

**Comment by rominf** [comment]
@artempyanykh It builds on ARM64 fine (I haven't try to install it though, since I don't have a suitable platform for this).

**Comment by artempyanykh** [comment]
Thanks for the contribution @rominf! I set up things on snapcraft, and everything seems to work just fine. I'll push a stable release shortly.

**Pull request merged**
