### PR TITLE
feat: Configurable link format

### PR DESCRIPTION
**Pull request by artempyanykh**
TODO:
- [x] Resolve more kinds of links using: document title, file path, file name, file stem (path wo/ ext).
- [x] Refactor the completion code to allow the configurability (#120)
- [x] Heading completion should resolve against doc using the logic above
- [x] Add a config option for wiki-links doc completion
- [x] Rename refactor should honor the kind of a file link (e.g. rename title shouldn't change a path-like link)
- [x] Docs

### CODE REVIEW

**Comment by artempyanykh** [comment]
Yeah, it's all a bit fuzzy. The reasoning for the current implementation is that if you stick to one particular style in your document folder and configure the completion accordingly, there won't be ambiguity in links.

I'm currently working on the completion which is a bit involved. Let's see how it plays out.

**Comment by edrex** [comment]
Thanks for leaving this open to get feedback.

Things that affect me:

- `[[Foo/Bar]]` should resolve to `./Foo/Bar.md`, at least. This works in emanote/obsidian
- `[[./Bar]]` should not match `./Foo/Bar.md` (although `[[Bar]]` may). This works in emanote + obsidian (basically emanote follows obsidian so I think they agree for most things)

A possible axis for config would be whether to search subdirs for "stem"-based links without an explicit `./`, `../`, or `/` prefix. Since most of the other tools are permissive here tho, I would tend to leave that option out. 

Also, I think this could be a future feature, but  `[[Title|Target]]` (gh wiki) vs `[[Target|Title]]` (obsidian etc) (see https://hackage.haskell.org/package/commonmark-extensions-0.2.3.3/docs/Commonmark-Extensions-Wikilinks.html) if/when marksman supports pipes in wiki links (I don't use these much but I think some people do).

I'd really like to put together a set of shared test cases and engage various tool authors to try to come to some consensus about the way wiki links should work. I had been plotting a lint/refactor tool to go along with it but honestly marksman seems like a good place for that to live (since, you know, it already does that), with .marksman.toml acting as a repo-wide policy description for linting.

**Comment by edrex** [comment]
I do notice that marksman makes my CPU spin for longer than I would think is needed (~45s on one core for my moderate size wiki with ~1400 fairly densely linked `md` files) but I hadn't used marksman much prior to this branch so I don't have a baseline to say it this is a regression. Are there any performance/stress test cases that could be used to detect a performance regression?

**Comment by artempyanykh** [comment]
@edrex perf tests is something I'd like to setup but haven't gotten to yet as it's a bit fiddly in the context of an LSP server.

I'm curious though, at what point do you see the CPU to spin? Is it during initialisation? Or when processing keystrokes? Or something else?

**Comment by edrex** [comment]
I guess I wouldn't worry as much about perf as getting the outputs right. Perf can come later IMO, even if it's a big regression.

**Comment by edrex** [comment]
Perf results: In a few days testing I found marksman turns 1 core into a heater for ~10s whenever a buffer in my moderate sized wiki

- is opened
- is changed

Switching buffers and moving around in the file, as expected, don't trigger the costly operation.

I haven't tested with your changes from today. 

Are this and the completion branch ready to start testing together?

**Comment by artempyanykh** [comment]
Thanks for testing @edrex! Calculating diagnostics might be the main factor here - it's not very efficient really. This would explain the CPU load on buffer change. But not when the buffer is open.

Diagnostics calc is done asynchronously outside of the main thread though, so I'd expect the server to be responsive and serving quickly other request like completion, symbols, etc. Does this match your experience @edrex?

**Comment by edrex** [comment]
Testing with alternate `wiki.style` values.

- `file?(-path)-stem` styles preserve stem case, which I very much appreciate.
- It would be cool to have a style which uses minimal paths. So from `foo/bar.md`
  - For sibling docs, just use the stem: `foo/baz.md -> baz` (or `./baz`?  not sure which is more broadly supported - test matrix soon)
  - For descendants of the current document directory, use relative path, eg `foo/ban/qux.md -> ban/qux` (or `./ban/qux`?)
  - Otherwise use path from root, like current `file-path-stem` style, eg `quux/waldo.md -> `/quux/waldo`
I think this would satisfy the needs of folks who want exactly resolved relative paths, but I can't guarantee that all the tools out there will resolve these paths correctly

Coming together nicely!

**Comment by edrex** [comment]
> This would explain.. But not when the buffer is open.
Oh, I meant "opened" as an event rather than a state. So when I first open a buffer.


> Diagnostics calc is done asynchronously outside of the main thread though, so I'd expect the server to be responsive and serving quickly other request like completion, symbols, etc. Does this match your experience @edrex?

Yeah, it does. I don't notice any delay in completion etc when CPU is high.

**Comment by edrex** [comment]
With the `file-(path-)?stem` styles, I notice that completion doesn't match the typed text against  document h1 titles (although those titles are shown in the result list entry). IMO, matching should happen against all possible fields (title, stem, path) and the setting should only affect what the search text is replaced with when a completion entry is selected.

>  It would be cool to have a style which uses minimal paths.

A minimal path wiki link style could be done in a follow-up PR, even as a "good first contrib" issue.

**Comment by artempyanykh** [comment]
>  IMO, matching should happen against all possible fields (title, stem, path)

This is how candidate search works now, yes (or at least is supposed to work 🙂).

> ... and the setting should only affect what the search text is replaced with when a completion entry is selected.

Yes, this is idea. But there's a couple layers of extra filtering involved: 
1. Through LSP's `filterText` attribute,
2. Through editor's own heuristics.

My first guess would be that it's `filterText` that is incorrect in some cases. @edrex could you give an example of a completion that doesn't work as you'd expect?

**Comment by srid** [comment]
I'm late to this thread, and haven't read all the comments above: but just wanted to state that it is generally a good idea to support the wiki-link convention that Obsidian itself supports. We don't have a clear standard on these things, but Obsidian seems to be the leader here, as far as future-proof Markdown notes goes.

Interesting extension, by the way. I might switch over from vscode-memo to this one in https://github.com/srid/emanote-template once it supports Obsidian/Emanote-style wikilinks.

**Comment by artempyanykh** [comment]
@edrex I think the problem with missing completions was due to wrong 'filter text' of a completion; this has been fixed in https://github.com/artempyanykh/marksman/pull/117/commits/8a9a5c33567cad7a1aa048f924d4458e891d6bb8.

I think the basic functionality should work now (but do give it a spin and report bugs :) ). There are several more things around file link resolution and completion that I want to improve, but this will likely go into separate PRs. @srid thanks for chiming in, by the way! "substring search in path hierarchy" makes sense.

**Comment by edrex** [comment]
> "sub-string match in path hierarchy".

@srid that's a helpful explaination. I feel like I understand the motivation a lot better now. Thanks! (meant to respond much earlier, echoing artempyanykh's reply). Only the tail of the path should match tho right?

Installed the release in my profile, and will be testing.

**Comment by srid** [comment]
Yes, it is similar to the [`tails`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-List.html#v:tails) function (but without the empty list). 

Here's emanote's implementation that returns the candidates:

https://github.com/srid/commonmark-wikilink/blob/72c880b5dbe8521f8c424c7bd39cb11b26e8dbb8/src/Commonmark/Extensions/WikiLink.hs#L151-L164

**Pull request merged**
