### PR TITLE
fix: Don't parse tags inside words & URLs

### LINKED ISSUE #265: Filter out hashtags within an url when listing tags
Following my comment https://github.com/artempyanykh/marksman/pull/262#issuecomment-1819612236 if I have an url like `https://docs.google.com/spreadsheets/d/1Rr7GcfjUwhZfylUk0FGL0Et4kYF5etl49OpRwRmhhlg/edit#gid=1116260529&range=D12` marksman will treat this as tag. Is it possible to filter out these cases?

Dunno if there are other edge cases that need futher filtering out.

### PR DESCRIPTION
**Pull request by TheBlob42**
fixes #265

It is an easy solution but it should cover at least all cases I can think of :thinking: 
Is there a nicer way for "early returns" in F#?

### CODE REVIEW

**Comment by TheBlob42** [comment]
Some non-alphanumeric characters are allowed in URLs that could potentially appear before the `#` character (`-`, `_`, `%`, `.`, `;`, `=` etc.). I personally don't know about any website that uses such URLs, but maybe someone knows a little more about it.

Here are some examples of **made up** valid URLs that my fix would not catch:
- `www.demo-#demo.com`
- `www.demo_#demo.com`
- `www.demo.com?#demo`

**Review by artempyanykh — APPROVED** [review]
Looks reasonable and will likely cover 99% of real-world cases. Thanks for the fix.

P.S. Early return is a bit of a pain in F#. You can emulate it using a computational expression and a `guard`, but this would be an overkill in this case.

**Comment by petobens** [comment]
Hi! So something like `https://tableau.com/#/site/Sales/views/elastico/Elstico` is expected not to be caught? Beyond theses cases (I have a few of those) things work much better now.

**Comment by TheBlob42** [comment]
Yes you are correct this is currently not caught. And with #268 now which allows `/` inside tags all of `#/site/Sales/views/elastico/Elstico` would be considered a tag :sweat_smile: to completely filter out URLs would require more work in regards to the parser

**Pull request merged**
