### PR TITLE
Use footnote reference tags for footnotes ...

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
Along-with some other minor changes

### CODE REVIEW

**Comment by artempyanykh** [comment]
Thanks @yashpalgoyal1304! Appreciate you improving the README!

**Comment by yashpalgoyal1304** [comment]
Welcome. Pleasure's all mine.

**Comment by yashpalgoyal1304** [comment]
I had some questions related to Markdown LSP landscape if you don't mind.

* What are differences in marksman and vs code's in-house [md-language-server] ?? I have stumbled across various places about mention of markdown LS, and each time, i am left wondering, why not VScode's one? 
* I mean, sure, there do exist different vendors of LS (like ms-intellisense, vs clangd), and I myself prefer to use the non-MS ones generally, but don't know why I can't find distinctions for markdown language.
* Also, do markdown LS benefit from the existing [HTML LS-es])? as these both language share quite some things i guess?

> The Markdown support in VS Code has been reimplemented to be a full-featured Language Server
>
> \- [vscode/v1_71#md-server]

[vscode/v1_71#md-server]: https://code.visualstudio.com/updates/v1_71#_markdown-language-server
[md-language-server]: https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features/server "MD-LS folder. This link found from the blog linked in changelog."
[HTML LS-es]: https://github.com/hrsh7th/vscode-langservers-extracted

**Comment by artempyanykh** [comment]
All good questions @yashpalgoyal1304!

> What are differences in marksman and vs code's in-house [md-language-server](https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features/server) ?? I have stumbled across various places about mention of markdown LS, and each time, i am left wondering, why not VScode's one?
I mean, sure, there do exist different vendors of LS (like ms-intellisense, vs clangd), and I myself prefer to use the non-MS ones generally, but don't know why I can't find distinctions for markdown LS.

1. Marksman (as a general LSP server for Markdown) was started before folks from VSCode decided to do their own thing. In fact, I reported some problems around integrating Marksman with VSCode (clash with built-in features) in [March 2021](https://github.com/microsoft/vscode/issues/118817) – more than a year before the [first commit in their Markdown LSP](https://github.com/microsoft/vscode-markdown-languageservice/commits/main?after=1a54bb82b2cf3f3818fc5517175becbe2690225c+209&branch=main&qualified_name=refs%2Fheads%2Fmain).  
2. Marksman has more features that I care about than VSCode's LSP: e.g. in addition to regular Markdown intelli-sense it supports wiki-links, which is particularly handy when you do note taking / knowledge-base management / Zettelkasten.
3. Marksman doesn't have a dependency on node, and is distributed as a standalone binary.
4. Marksman has integrations with many editors: neovim/LSP, Emacs (LSP-mode and Eglot), Helix, Sublime Text, and VSCode.
5. Most importantly, it works for me... and for many others. It's cool that MS released a similar markdown LS. People can use whatever suits them best. Let a thousand flowers bloom 😉

> Also, do markdown LS benefit from the existing [HTML LS-es](https://github.com/hrsh7th/vscode-langservers-extracted))? as these both language share quite some things i guess?

Hm, maybe if you squint hard enough... Some infrastructure things are common across LSP servers, but Markdown and HTML are different languages and require different treatment.

Hope this helps!

**Comment by yashpalgoyal1304** [comment]
> 5\. Let a thousand flowers bloom 😉

ofcourse haha :)




> Hope this helps!

yes it did, thanks :)

**Pull request merged**
